apiVersion: v1
kind: Service
metadata:
  name: quakewatch-service
  labels:
    app: quakewatch
spec:
  selector:
    app: quakewatch
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer